# Generated by Django 5.0.4 on 2024-04-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("important", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
